baseURL: 'http://www.gregburek.com/'
languageCode: en-us
title: Greg Burek
theme: hugo-flex
enableRobotsTXT: true
params:
  color: '#FF3366'
  social:
    - name: Github
      icon: github
      url: 'https://github.com/gregburek'
    - name: Twitter
      icon: twitter
      url: 'https://twitter.com/gregburek'
    - name: LinkedIn
      icon: linkedin
      url: 'https://www.linkedin.com/in/gregburek/'
permalinks:
  posts: '/:year/:month/:day/:title/'
menu:
  nav:
  - name: About
    url: about/
    weight: 1
  - name: Posts
    url: post/
    weight: 2
  - name: Tags
    url: tags/
    weight: 3