baseURL: 'https://www.gregburek.com/'
languageCode: en-us
title: Greg Burek
theme: hugo-flex
enableRobotsTXT: true
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
params:
  rss: To subscribe to this RSS feed, copy its address and paste it into your
    favorite feed reader.
  color: '#FF3366'
  footer: ""
permalinks:
  posts: '/:year/:month/:day/:title/'
menu:
  nav:
  - name: About
    url: about/
    weight: 1
  - name: Posts
    url: posts/
    weight: 2
  - name: Tags
    url: tags/
    weight: 3
  - name: RSS
    url: index.xml
    weight: 4

